# Generated by Django 5.2.1 on 2025-05-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="crypto_type",
            field=models.CharField(
                choices=[("eth", "Ethereum"), ("bnb", "BNB"), ("polygon", "Polygon")],
                default="eth",
                max_length=10,
            ),
        ),
    ]
