# Generated by Django 5.2.1 on 2025-05-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_wallet_crypto_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="crypto_type",
            field=models.CharField(
                choices=[
                    ("ethereum", "Ethereum"),
                    ("bnb", "BNB"),
                    ("polygon", "Polygon"),
                ],
                default="ethereum",
                max_length=10,
            ),
        ),
    ]
